# Generated by Django 5.0.3 on 2024-04-02 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeframe', models.DurationField()),
                ('close', models.FloatField()),
                ('ema20', models.FloatField(blank=True, null=True)),
                ('ema50', models.FloatField(blank=True, null=True)),
                ('ema100', models.FloatField(blank=True, null=True)),
                ('ema200', models.FloatField(blank=True, null=True)),
                ('trend', models.FloatField(choices=[("1", 'Upwards'), ("-1", 'Downwards'), ("0", 'Sideways')])),
                ('monhigh', models.FloatField()),
                ('monlow', models.FloatField()),
                ('monmid', models.FloatField()),
                ('twenty_greater_than_fifty', models.BooleanField()),
                ('fifty_greater_than_hundred', models.BooleanField()),
                ('hundred_greater_than_twohundred', models.BooleanField()),
                ('close_greater_than_hundred', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ema_records', to='currency.currency')),
            ],
            options={
                'verbose_name': 'EMA Record',
                'verbose_name_plural': 'EMA Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
