# Generated by Django 5.0.3 on 2024-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emarecord',
            name='trend',
            field=models.IntegerField(choices=[("1", 'Upwards'), ("-1", 'Downwards'), ("0", 'Sideways')]),
        ),
    ]
