# Generated by Django 5.0.3 on 2024-04-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_currency_options_and_more'),
        ('ema', '0003_alter_emarecord_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emarecord',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ema_records', to='currency.currency'),
        ),
    ]
