# Generated by Django 5.0.3 on 2024-05-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currency_category_alter_currency_symbol'),
        ('ema', '0004_alter_emarecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emarecord',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ema_records', to='currency.currency'),
        ),
    ]
