# Generated by Django 5.0.3 on 2024-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_authtoken_unique_together_alter_authtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='name',
            field=models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=200),
        ),
    ]
