# Generated by Django 5.0.3 on 2024-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_alter_passwordresettoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='name',
            field=models.CharField(default=None, help_text='A free-form name for the password reset token. Need not be unique. 200 characters max.', max_length=200),
        ),
    ]
