# Generated by Django 5.0.3 on 2024-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_passwordresettoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Once token expires, clients cannot use it anymore.', null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='name',
            field=models.CharField(default=None, help_text='A free-form name for the token. Need not be unique. 200 characters max.', max_length=200),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='revoked',
            field=models.BooleanField(blank=True, default=False, help_text='If the token is revoked, clients cannot use it anymore. (This cannot be undone.)'),
        ),
    ]
